//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIsLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int userID { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> registerDate { get; set; }
        public string note { get; set; }
        public Nullable<int> rate { get; set; }
    }
}
